### ISSUE TITLE
character missing

### ISSUE THREAD

**Issue by obi134** [SgtSeppel/nibeuplink#2]
The value of the following line

```
<span class="AutoUpdateValue ID47407">nicht verw.</span>
```

is parsed to

```
'nict verw.'
```

**Comment by SgtSeppel** [comment]
This was due to some quite dirty hack to remove trailing "h" for "hours" in some strings. 
I modified the regex slightly so that this should not occur anymore.
Please note that parsing of string items is not really supported as of now.
Please re-test with commit a62c5124e1aae1ce8eff734592ad879be8230ef8

**Comment by obi134** [comment]
It's working, thank you for fast bugfix
